version: "3.6"
services:
  #
  api-gateway:
    container_name: "ms_api-gateway"
    build: "./api-gateway"
    depends_on:
      - listings-service
      - users-service
    ports:
      - "7000:7000"
    volumes:
      - ./api-gateway:/opt/app

    entrypoint: "./entrypoint.sh"

  #
  front-app:
    container_name: "ms_front-app"
    build: "./classifieds-app"
    ports:
      - "7001:7001"
      - "1234:1234"
      - "1235:1235"
    volumes:
      - ./classifieds-app:/opt/app

      - type: bind
        source: ./classifieds-app/.env.example
        target: /opt/app/.env

    entrypoint: "./entrypoint.sh"
    environment:
      - CHOKIDAR_USEPOLLING=1

  #
  listings-service:
    container_name: "ms_listings_api"
    build: "./listings-service"
    depends_on:
      - listings-service-db
    environment:
      - DB_URI=mysql://root:password@listings-service-db/db?charset=UTF8
    ports:
      - "7100:7100"
    volumes:
      - ./listings-service:/opt/app
    entrypoint: "./entrypoint.sh"

  #
  listings-service-db:
    container_name: "ms_listings_db"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:5.7.20
    ports:
      - 0.0.0.0:7200:3306

  #
  users-service:
    container_name: "ms_users_api"
    build: "./users-service"
    depends_on:
      - users-service-db
    environment:
      - DB_URI=mysql://root:password@users-service-db/db?charset=UTF8
    ports:
      - "7101:7101"
    volumes:
      - ./users-service:/opt/app
    entrypoint: "./entrypoint.sh"

  #
  users-service-db:
    container_name: "ms_users_db"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:5.7.20
    ports:
      - 0.0.0.0:7201:3306
